const dummyProducts = [
    {
        id: 1,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Sakura",
        productCode: "PRF001",
        category: "Parfum Malam",
        composition: ["Alcohol", "Sakura Extract", "Aqua"],
        price: 120000,
        stock: 50,
        images: [],
        variations: [
            { name: "Aroma", options: ["Sakura", "Melati","Mawar", "Oli","Bunga", "Ban"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["50 ml", "100 ml"] },
        ],
    },
    {
        id: 2,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Rose",
        productCode: "PRF002",
        category: "Parfum Siang",
        composition: ["Alcohol", "Rose Oil", "Aqua"],
        price: 150000,
        stock: 30,
        images: [],
        variations: [
            { name: "Aroma", options: ["Rose", "Lily"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["30 ml", "60 ml"] },
        ],
    },
    {
        id: 3,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Vanilla",
        productCode: "PRF003",
        category: "Parfum Malam",
        composition: ["Alcohol", "Vanilla Extract", "Aqua"],
        price: 100000,
        stock: 40,
        images: [],
        variations: [
            { name: "Aroma", options: ["Vanilla", "Coconut"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["75 ml", "150 ml"] },
        ],
    },
    {
        id: 4,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Ocean",
        productCode: "PRF004",
        category: "Parfum Siang",
        composition: ["Alcohol", "Oceanic Fragrance", "Aqua"],
        price: 130000,
        stock: 60,
        images: [],
        variations: [
            { name: "Aroma", options: ["Ocean", "Mint"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["100 ml", "200 ml"] },
        ],
    },
    {
        id: 5,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Citrus",
        productCode: "PRF005",
        category: "Parfum Malam",
        composition: ["Alcohol", "Citrus Oil", "Aqua"],
        price: 110000,
        stock: 25,
        images: [],
        variations: [
            { name: "Aroma", options: ["Citrus", "Lemon"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["50 ml", "100 ml"] },
        ],
    },
        {
        id: 6,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Citrus",
        productCode: "PRF005",
        category: "Parfum Malam",
        composition: ["Alcohol", "Citrus Oil", "Aqua"],
        price: 110000,
        stock: 25,
        images: [],
        variations: [
            { name: "Aroma", options: ["Citrus", "Lemon"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["50 ml", "100 ml"] },
        ],
    },
        {
        id: 7,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Citrus",
        productCode: "PRF005",
        category: "Parfum Malam",
        composition: ["Alcohol", "Citrus Oil", "Aqua"],
        price: 110000,
        stock: 25,
        images: [],
        variations: [
            { name: "Aroma", options: ["Citrus", "Lemon"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["50 ml", "100 ml"] },
        ],
    },
        {
        id: 8,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Citrus",
        productCode: "PRF005",
        category: "Parfum Malam",
        composition: ["Alcohol", "Citrus Oil", "Aqua"],
        price: 110000,
        stock: 25,
        images: [],
        variations: [
            { name: "Aroma", options: ["Citrus", "Lemon"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["50 ml", "100 ml"] },
        ],
    },
        {
        id: 9,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Citrus",
        productCode: "PRF005",
        category: "Parfum Malam",
        composition: ["Alcohol", "Citrus Oil", "Aqua"],
        price: 110000,
        stock: 25,
        images: [],
        variations: [
            { name: "Aroma", options: ["Citrus", "Lemon"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["50 ml", "100 ml"] },
        ],
    },
        {
        id: 10,
        image: "/images/logos/logo-mini-new.png",
        productName: "Parfum Citrus",
        productCode: "PRF005",
        category: "Parfum Malam",
        composition: ["Alcohol", "Citrus Oil", "Aqua"],
        price: 110000,
        stock: 25,
        images: [],
        variations: [
            { name: "Aroma", options: ["Citrus", "Lemon"],image: "/images/logos/logo-mini-new.png" },
            { name: "Volume", options: ["50 ml", "100 ml"] },
        ],
    },
];

export default dummyProducts;