name: CI/CD
on :
  push:
    branches: [ setting-template ]
  pull_request:
    branches: [ setting-template ]

  workflow_dispatch:

jobs:
  web-deploy:
    name: auto deploy
    runs-on: ubuntu-latest

    steps:
    - name: get latest code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy ke Server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /www/wwwroot/pos-parfum
        git pull origin setting-template
        npm install
        npm run build
        pm2 restart all  # Jika pakai PM2, sesuaikan jika pakai layanan lain
        EOF

    - name: FTP Deploy
    # You may pin to the exact commit or the version.
    # uses: SamKirkland/FTP-Deploy-Action@8a24039354ee91000cb948cb4a1dbdf1a1b94a3c
      uses: SamKirkland/FTP-Deploy-Action@v4.3.1
      with:
        # ftp server
        server: 202.73.26.148
        # ftp username
        username: ftp_pos_parfum
        # ftp password
        password: pnM66skxWejMEmJM
        # Server port to connect to (read your web hosts docs)
        port: 21
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftp
        # An array of glob patterns, these files will not be included in the publish/delete process
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
